### ISSUE TITLE
panic with no sinks/clustersinks

### ISSUE THREAD

**Issue by arichardet** [pivotal-cf/fluent-bit-out-syslog#20]
fluent-bit-out-syslog version 0.9

With the syslog output configured with no Sinks or ClusterSinks, the fluent-bit pods panic and have a Status=Error.

Configuration:
```
[INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

[FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On

[OUTPUT]
        Name syslog
        Match *
        Addr <redacted>
```

Logs from one of the fluent-bit pods:

```
[2018/11/21 15:28:14] [ info] [engine] started (pid=1)
2018/11/21 15:28:14 [out_syslog] sinks =
2018/11/21 15:28:14 [out_syslog] unable to unmarshal: unexpected end of JSON input
[2018/11/21 15:28:14] [ info] [filter_kube] https=1 host=kubernetes.default.svc.cluster.local port=443
[2018/11/21 15:28:14] [ info] [filter_kube] local POD info OK
[2018/11/21 15:28:14] [ info] [filter_kube] testing connectivity with API server...
[2018/11/21 15:28:14] [ info] [filter_kube] API server connectivity OK
[2018/11/21 15:28:14] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fd4e2bb9e89]

goroutine 17 [running, locked to thread]:
github.com/pivotal-cf/fluent-bit-out-syslog/pkg/syslog.(*Out).Write(0x0, 0xc420154210, 0x2fde675f, 0xed3877080, 0x7fd4e31dc3c0, 0xc4201a4000, 0x83, 0xc42016a0e0, 0x3)
	/go/src/github.com/pivotal-cf/fluent-bit-out-syslog/pkg/syslog/out.go:81 +0xa9
main.FLBPluginFlush(0x7fd4de275440, 0xc40000255a, 0x7fd4e32598c0, 0xc42005fed8)
	/go/src/github.com/pivotal-cf/fluent-bit-out-syslog/cmd/main.go:62 +0x108
main._cgoexpwrap_522c5543b4e9_FLBPluginFlush(0x7fd4de275440, 0x255a, 0x7fd4e32598c0, 0x0)
	_cgo_gotypes.go:82 +0x3f
```

**Comment by arichardet** [comment]
The logs posted in previous comment were from an older version, my apologies. See update below:

```
Fluent-Bit v0.14.5
  inputs.conf: |
Copyright (C) Treasure Data

[2018/11/21 17:59:09] [ info] [engine] started (pid=1)
2018/11/21 17:59:09 [out_syslog] ERROR: sinks can't be empty
[2018/11/21 17:59:09] [ info] [filter_kube] https=1 host=kubernetes.default.svc.cluster.local port=443
[2018/11/21 17:59:09] [ info] [filter_kube] local POD info OK
[2018/11/21 17:59:09] [ info] [filter_kube] testing connectivity with API server...
[2018/11/21 17:59:09] [ info] [filter_kube] API server connectivity OK
[2018/11/21 17:59:09] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7efec684cb7f]

goroutine 17 [running, locked to thread]:
github.com/pivotal-cf/fluent-bit-out-syslog/pkg/syslog.(*Out).Write(0x0, 0xc00009be30, 0x1e4fd614, 0xed38793cf, 0x7efec6fdc300, 0xc00015e000, 0x83, 0x7efec6cc0b80, 0xc000050e80)
	/root/pkg/syslog/out.go:93 +0x8f
main.FLBPluginFlush(0x7efec70b9a00, 0xc0000028d2, 0x7efec705ca00, 0x7efec6cbfed8)
	/root/cmd/main.go:92 +0x131
main._cgoexpwrap_ad7cbfc89713_FLBPluginFlush(0x7efec70b9a00, 0x2d383130000028d2, 0x7efec705ca00, 0x352e37333a38353a)
	_cgo_gotypes.go:88 +0x3f
```

**Comment by ahevenor** [comment]
@arichardet Thanks for filing this. This is not desired behavior but hadn't come up in our testing. We just reviewed and have prioritized this in our backlog.

**Comment by ahevenor** [comment]
@arichardet We fixed the issue by doing another check in the `FLBPluginFlush` however this is not ideal.

We had a discussion with Eduardo (maintainer of fluent-bit) and he confirmed that the behavior is unintended. We created this github [issue](https://github.com/fluent/fluent-bit/issues/949) to track with all the relevant context. We'll be cutting a new release today to address this.

**Comment by jasonkeene** [comment]
The new release is now available: https://github.com/pivotal-cf/fluent-bit-out-syslog/releases/tag/v0.11
